version: "3.2"
networks:
  zkstack:
    driver: bridge
services:
  zkstack_geth:
    image: "matterlabs/geth:latest"
    ports:
      - "127.0.0.1:18545:8545"
      - "127.0.0.1:18546:8546"
    volumes:
      - type: bind
        source: ./volumes/geth
        target: /var/lib/geth/data
    networks:
      - zkstack
    container_name: zkstack_geth
  zkstack_postgres:
    image: "postgres:14"
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - type: bind
        source: ./volumes/postgres
        target: /var/lib/postgresql/data
    environment:
      # We bind only to 127.0.0.1, so setting insecure password is acceptable here
      - POSTGRES_PASSWORD=notsecurepassword
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
    networks:
      - zkstack
    container_name: zkstack_postgres
